### ISSUE TITLE
Question(/Bug?): Vex not added in brunch compile

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [HubSpot/vex#123]
I have vex installed with bower. I use brunch to compile everything together in a `vendor.js`. Tether, drop and other HubSpot libraries seem to be added just fine, but not Vex. Any ideas why this is? Have I messed something up, or is there maybe something wrong with the vex `bower.json`?

My `bower.json`

```
{
  "name": "angular-brunch-seed",
  "version": "0.3.0",
  "main": "_public/js/app.js",
  "ignore": [
    "**/.*",
    "node_modules",
    "components"
  ],
  "dependencies": {
    "console-polyfill": "~0.1.1",
    "jquery": ">=2.1.1",
    "angular": "~1.2.16",
    "angular-sanitize": "~1.2.16",
    "angular-resource": "~1.2.16",
    "angular-route": "~1.2.16",
    "angular-cookies": "~1.2.16",
    "angular-mocks": "~1.2.16",
    "components-underscore": "~1.5.2",
    "scroll-reveal": "~2.2",
    "d3": "~3.4.12",
    "leaflet": "~0.7.3",
    "leaflet.markercluster": "0.4.0-hotfix.1",
    "leaflet-providers": "~1.0.24",
    "Leaflet.label": "~0.2.1",
    "Leaflet.awesome-markers": "~2.0.2",
    "BOB": "~0.0.8",
    "vex": "~2.3.2",
    "offline": "~0.7.11",
    "drop": "~0.5.5",
    "shepherd.js": "~0.7.1"
  },
  "overrides": {
    "foundation": {
      "ignore": [
        "*"
      ]
    },
    "modernizr": {
      "main": "_public/js/app.js"
    },
    "angular-mocks": {
      "main": "README.md"
    }
  }
}
```

My brunch `config.coffee`

```
exports.config =
  # See docs at http://brunch.readthedocs.org/en/latest/config.html.
  conventions:
    assets:  /^app[\/\\]+assets[\/\\]+/
    ignored: /^(bower_components[\/\\]+foundation|app[\/\\]+styles[\/\\]+overrides|(.*?[\/\\]+)?[_]\w*)/
  modules:
    definition: false
    wrapper: false
  paths:
    public: '_public'
    jadeCompileTrigger: '.compile-jade'  # Defaults to 'js/dontUseMe'.
  files:
    javascripts:
      joinTo:
        'js/app.js': /^app/
        'js/vendor.js': /^(bower_components|vendor)/
      order:
        after: [
          "app/scripts/message_handler.coffee",
          "app/scripts/connector.coffee",
          "app/scripts/companyname_buttons.coffee",
          "app/scripts/gem_adapter.coffee",
        ]

    stylesheets:
      joinTo:
        'css/app.css': /^(app|vendor|bower_components)/
      order:
        before: [
          'app/styles/app.scss'
        ]
  plugins:
    jaded:
      staticPatterns: /^app[\/|\\](.+)\.jade$/
      jade:
        pretty: yes # Adds pretty-indentation whitespaces to output (false by default)
    # autoReload:
    #   enabled:
    #     css: on
    #     js: on
    #     assets: off
    #   port: [1234, 2345, 3456]
    #   delay: 200 if require('os').platform() is 'win32'
  # Enable or disable minifying of result js / css files.
  minify: false
```

Building with command `brunch build`.
