### ISSUE TITLE
Removing background overlay

### ISSUE THREAD

**Issue by farukuzun** [HubSpot/vex#153]
Hi,

Is it possible to remove background overlay?, i'm using something like this;

```	
vex.dialog.confirm({
  			message: 'Are you absolutely sure you want to destroy the alien planet?',
  			overlayCSS: {display: 'none'}, 
  			callback: function(value) {
  			  return console.log(value ? 'Successfully destroyed the planet.' : 'Chicken.');
  			}
});
```

But still not able to interact with other elements on page while dialog is on.

**Comment by adamschwartz** [comment]
```CSS
.vex {
  pointer-events: none
}

.vex-content {
  pointer-events: all
}

.vex-overlay {
  display: none
}
```
