### ISSUE TITLE
Long vex.dialog.alert displays text at bottom not from top

### ISSUE THREAD

**Issue by DanLuczywo** [HubSpot/vex#205]
I'm using the vex.dialog.alert with vex-theme-top to display the EULA in my app when it's first run but it always displays the bottom of the text with the OK button.

Is there any way to force the top of the text to be displayed?

Thanks.

**Comment by bbatliner** [comment]
Do you have a screenshot to show what's going on? I can maybe help more if I understand the issue.

**Comment by DanLuczywo** [comment]
![screenshot_2017-02-20-17-23-08 1](https://cloud.githubusercontent.com/assets/23166859/23135643/528683f0-f791-11e6-968d-15d7e46a6773.png)

So the first time the user runs the app they have to accept the EULA. I've used vex.dialog.alert to show this but would like the alert to display from the beginning of the EULA and then scroll down to the accept button.

**Comment by DanLuczywo** [comment]
Did you have any thoughts or do I need to try and explain a bit more???

**Comment by bbatliner** [comment]
My apologies - you explained it well.

I experimented with the same problem you're having (`vex-theme-top` and too much text) and found a solution, let me know if it's what you're looking for.

For whatever reason, a vex that overflows will scroll to the bottom by default. We can get around this in a slightly hacky way by doing two things:

1. Removing the dropin animation timing for the theme. Add this to your CSS to override vex, or edit the file directly:

```css
.vex.vex-theme-top .vex-content {
    animation: vex-dropin 0;
    -webkit-animation: vex-dropin 0;
    -moz-animation: vex-dropin 0;
    -ms-animation: vex-dropin 0;
    -o-animation: vex-dropin 0;
    -webkit-backface-visibility: hidden;
}
```

2. Scrolling the vex content back to the top after it's opened:

```js
afterOpen: function () {
    setTimeout(() => {
        // Either of these lines will do the trick, depending on what browsers you need to support.
        this.rootEl.scrollTop = 0
        this.contentEl.scrollIntoView(true)
    }, 0)
}
```

This is what I found with 10 minutes of hacky bug fixing, if you find a better solution I'd love to hear it. Thanks!
