### ISSUE TITLE
How to render contents of a hidden div?

### ISSUE THREAD

**Issue by exalted** [HubSpot/vex#89]
Here's a quick question:

Suppose you have a `div` such as:

``` html
<div id="hello" class="whatever">
    <p>Hello, World! ;-)</p>
</div>
```

With a little bit of styling:

``` css
.whatever {
  visibility: hidden;
  width: 100%;
  height: 88px;
  background-color: rgb(19, 188, 175);
}
```

Currenty, I do `open` a dialog using vex like:

``` js
var hello = $('#hello');
vex.open({
  content: hello.wrap('<div></div>').parent().html(),
  contentCSS: {
    width: '320px',
    height: hello.css('height')
  }
});
```

As you may have guessed this would open the dialog with `visibility: hidden;` `div` inside of it. Instead, I would like to "hide" the div inside the page, but "show" inside the dialog.

I'd appreciate a little bit of help please.

Thank you.
